
#type: args

train:
  epochs: 50
  batch_size: 32 
  lr: 1.0e-3 

diffusion:
  size: 32 
  layers: 3 
  channels: 128 
  num_heads: 8
  ff_dim: 512 
  time_points: 40 
  diffusion_embedding_dim: 128
  time_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 50